//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityTracking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("£")]
        public char CurrencySymbol {
            get {
                return ((char)(this["CurrencySymbol"]));
            }
            set {
                this["CurrencySymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MaxRecordsPerDoc {
            get {
                return ((int)(this["MaxRecordsPerDoc"]));
            }
            set {
                this["MaxRecordsPerDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\APPTEST\\RECORDS")]
        public string RecordFileLocation {
            get {
                return ((string)(this["RecordFileLocation"]));
            }
            set {
                this["RecordFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\APPTEST\\APPRCRD_SCHEMA.xsd")]
        public string SchemaFileLoc {
            get {
                return ((string)(this["SchemaFileLoc"]));
            }
            set {
                this["SchemaFileLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APPRCRD_")]
        public string XMLRecordName {
            get {
                return ((string)(this["XMLRecordName"]));
            }
            set {
                this["XMLRecordName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd/MMM/yy   HH:mm")]
        public string RecordDateFormat {
            get {
                return ((string)(this["RecordDateFormat"]));
            }
            set {
                this["RecordDateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public double DaysPerMonth {
            get {
                return ((double)(this["DaysPerMonth"]));
            }
            set {
                this["DaysPerMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("365.25")]
        public double DaysPerYear {
            get {
                return ((double)(this["DaysPerYear"]));
            }
            set {
                this["DaysPerYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedDatePeriodFilterName {
            get {
                return ((string)(this["SelectedDatePeriodFilterName"]));
            }
            set {
                this["SelectedDatePeriodFilterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WeekStartsOnDay {
            get {
                return ((int)(this["WeekStartsOnDay"]));
            }
            set {
                this["WeekStartsOnDay"] = value;
            }
        }
    }
}
